version: '3.8'

services:
  genesis:
    build: .
    image: genesis:latest
    container_name: genesis_container
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
    ports:
      - "7860:7860"
    volumes:
      - .:/home/ci/app
      - ./data:/home/ci/data
      - ./frames:/home/ci/frames
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 8G
    shm_size: '8gb'
    healthcheck:
      test: ["CMD", "python3.11", "-c", "import genesis; print('Genesis health check passed')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
